### ISSUE TITLE
Contributors needed

### ISSUE THREAD

**Issue by FallenAngel97** [FallenAngel97/dynosign#1]
Hello everyone. My name is Alexey and I'm maintainer of this repo.
The goal of **DynoSign** is to provide the UI/UX experience to such platforms as Linux, where there is a lack of such prototyping-drawing-animation tools. This project will be written in JavaScript with help of Electron, React and Redux frameworks/libraries. 
For now, the base application exists, which demonstrates the basic workflow.
Any contributions are welcome. This includes, but not limits to such as:

- Drawings (Any designer, who finds this project interesting, can contribute with assets)
- Code (New features implementation, bug fixes, etc.)
- Translations (Why not? Let's make this application international :smile: )
- Tests (Improvement of quality is a must-have, so thanks for any testing that you have accomplished)

**Comment by StarTrekRules** [comment]
I might be able to help as I know javascript, but not react or electron yet.
I am fast at learning from documentation.

**Comment by FallenAngel97** [comment]
@StarTrekRules, that's great! Thanks :)
How should we organise work then? I can leave "TODO" in comments or etc. 
For now, there is a thing, that I want to implement: https://codepen.io/retrofuturistic/pen/tlbHE
I do have the logic of moving and dragging-dropping, but not enough visuals. I mean, the line is not appearing above or below. Let's take this for example. Should it be reported as [BUG] or somehow other?
I'm open to your suggestions

**Comment by FallenAngel97** [comment]
Also, as off-topic. What are you thinking about default color scheme? Is it okay, or it's necessary to change it?

**Comment by StarTrekRules** [comment]
@FallenAngel97 My discord is The Reverse Flash#6087
I cannot give you any opinions yet as I am STILL trying to get it to compile and run.
I just fixed one problem with font-manager and now all it does is open a blank window

**Comment by FallenAngel97** [comment]
Please, run in the second window(terminal) `npm run watch`
And refresh the electron window. Maybe this is the issue
I haven't yet used discord, I'll give it a try, thanks. ASAP i got it, I will notify you

**Comment by nilamjadhav** [comment]
Hi,
I wanted to contribute for this project? How can I help? I know javascript and react

**Comment by FallenAngel97** [comment]
> Hi,
> I wanted to contribute for this project? How can I help? I know javascript and react

Hello! Thanks for your proposition. Firstly, create fork. Make your changes. Then submit Pull request, which I will review.
You can fix the image saving into the binary formats, such as .png/.jpg-s, if you want to help this project

**Comment by adityawankhede5** [comment]
hey, I know JS and React JS and I love working with React JS. I would like to contribute to this project.

**Comment by FallenAngel97** [comment]
> 
> 
> hey, I know JS and React JS and I love working with React JS. I would like to contribute to this project.

Hello. The previous comment still valid, you can try to make a fix for binary formats

**Comment by Blargian** [comment]
Hello. Is this project still going? I have a little bit of experience with JS and React and I want to learn more about Electron. I'm looking for a project to contribute to.

**Comment by FallenAngel97** [comment]
Due to the lack of time and absence of contributors, this project will be archived. 
You can still use for UX [Figma](https://figma.com) and for the open-source standalone graphical editor, I have switched to [Krita](https://krita.org)
